config/routes.rb
Rails.application.routes.draw do
  root "patient#index"

 # namespace :directory_name do
  #  resources :controller1, :controller2
 # end

 # scope :module => "admin" do
 #   resources :controller1, :controller2
 # end

  # resources :patient, only: [:post]
  # resources :patient, except: [:show]


  resources :patient, :except => [ :new, :create, :edit, :update, :show, :destroy] do

    member do #member require id
      get :view_single_info
      get :edit_page
      get :delete_pateint
      patch :update_pateint
    end

    collection do #collection does't require any id
      get :view_page
      get :add_page
      post :save_pateint
    end
  end
=begin
  resources :doctor, :except => [ :new, :create, :edit, :update, :show, :destroy] do

    member do #member require id
      get :view_single_info
      get :edit_page
      get :delete_pateint
      patch :update_pateint
    end

    collection do #collection does't require any id
      get :view_page
      get :add_page
      post :save_pateint
    end
  end
=end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  has_many :doctor
  has_many :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
 # before_action :add_page
 # before_filter :view_page
  def index
    redirect_to view_page_patient_index_url
  end

  def view_page
    flash[:notice] = "Welcome to view page"
    @pateint_info = Patient.all

    #@pateint_info = Patient.all
    #@pateint_info = Patient.take(2) #fetch 2 data from DB
    #@pateint_info = Patient.find([8,9]) #set limit for all data
    #@pateint_info = Patient.first(3) #fetch first 3 data
    #@pateint_info = Patient.order(:text).last(3) #fetch by order use for DESC='last' and ASC by default
    #@pateint_info = Patient.where(title:'reter',id:21) #fetch by condition
  end

  def view_single_info
    @every_pateint_info = Patient.find(params[:id])
  end

  def add_page

  end

  def edit_page
    @patient_update = Patient.find(params[:id])
  end

  def save_pateint
    @patient_save = Patient.new(patient_permission)

    if @patient_save.save
      flash[:info] = "Save successfully"
      redirect_to view_page_patient_index_url
    end

  end

  def update_pateint
    @patient_update = Patient.find(params[:id])
    if @patient_update.update(patient_permission)
     flash[:info] = "Update successfully"
     redirect_to view_page_patient_index_url
    end

  end

  def delete_pateint
    @delete_pateint = Patient.find(params[:id])
    @delete_pateint.destroy

    flash[:info] = "Information successfully deleted..."
    redirect_to view_page_patient_index_url
  end

  private
    def patient_permission
      params.require(:patient).permit(:name, :address, :problem)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient_helper.rb
module PatientHelper
  def country_name()
    country_list = "India, China, Bangladesh"
  end  	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patient/_links.html.erb
<!--
 This page is example of partials
-->
<table>
  <tr>
    <td><%= link_to "Go to view page", view_page_patient_index_path %></td>
    <td>    </td>
    <td><%= link_to "Go to add page", add_page_patient_index_path %><br></td>
  </tr>
  <tr>
    <td rowspan=2 >
      Services available only in following countries :
      <b><%= country_name()  %></b> 	
    </td>
  </tr>
</table>

app/views/patient/add_page.html.erb
<%=render partial: "links"%>
<h1>Patient add_page</h1>
<p>Find me in app/views/patient/add_page.html.erb</p>

<%= form_for :patient, url: save_pateint_patient_index_path do |f| %>

 <p>
   <%=f.label :Enter_Name %>
   <%=f.text_field :name, id: :pateint_name %>
 </p>

 <p>
   <%=f.label :Enter_problem %>
   <%=f.text_field :problem, id: :patient_problem %>
 </p>

 <p>
   <%=f.label :Enter_Address %>
   <%=f.text_area :address, id: :pateint_address %>
 </p>

 <%=f.submit %>
<% end %>

app/views/patient/edit_page.html.erb
<%=render partial: "links"%>
<h1>Update page</h1>
<%= form_for @patient_update, url: update_pateint_patient_path, method: :patch do |f| %>

    <p>
      <%=f.label :Enter_Name %>
      <%=f.text_field :name, id: :pateint_name %>
    </p>

    <p>
      <%=f.label :Enter_problem %>
      <%=f.text_field :problem, id: :patient_problem %>
    </p>

    <p>
      <%=f.label :Enter_Address %>
      <%=f.text_area :address, id: :pateint_address %>
    </p>

    <%=f.submit %>
<% end %>

app/views/patient/view_page.html.erb
<%=render partial: "links"%>
<h1>Patient view_page</h1>

<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<p style = "color:darkgreen"><%= flash[:info] %></p>
<table border = "1">
  <tr>
    <td>Sno.</td>
    <td>Name</td>
    <td>Address</td>
    <td>Problem</td>
    <td>Action</td>
  </tr>

  <% count=1
    @pateint_info.find_each do |pateints| %>
      <tr>
        <td><%= count %></td>
        <td><%= pateints.name %></td>
        <td><%= pateints.address %></td>
        <td><%= pateints.problem %></td>
        <td>
          <%= link_to "view", view_single_info_patient_path(pateints) %> |
          <%= link_to "update", edit_page_patient_path(pateints) %> |
          <%= link_to "delete", delete_pateint_patient_path(pateints) %> |
        </td>
      </tr>
      <% count+=1
    end 
  %>
</table>

app/views/patient/view_single_info.html.erb
<%=render partial: "links"%>
<h1>Patient Single Info</h1>
<h3>Normal view</h3>
<b>Name:</b> <%=@every_pateint_info.name %><br>
<b>Problem:</b> <%=@every_pateint_info.problem %><br>
<b>Address:</b> <%=@every_pateint_info.address %><br>

<h3>JSON view</h3>
<%=@every_pateint_info.as_json(root: true) %>